In [2]:
import numpy as np

## Transpose

In [3]:
A = np.array([[1,2,3], [4,5,6]])
R = np.einsum("ij->ji", A)
print(R)

[[1 4]
 [2 5]
 [3 6]]


## Diagonal, trace

In [4]:
A = np.eye(10)
diag = np.einsum('ii->i', A)
trace =np.einsum('ii->', A)
print(diag)
print(trace)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
10.0


## Summation

In [5]:
A = np.array([[1,2,3], [4,5,6]])
R = np.einsum("ij->", A)
print(R)

21


In [1]:
A = np.array([[1,2,3], [4,5,6]])
row_sum = np.einsum("ij->i", A)
col_sum =np.einsum("ij->j", A)
print(row_sum)
print(col_sum)

[ 6 15]
[5 7 9]


## Multiplication

In [6]:
x = np.array([-1, -10, -100])
y = np.array([1, 10, 100])
dot = np.einsum('i,i->', x, y )
outer = np.einsum('i,j->ij', x,y)
print(dot)
print(outer)

-10101
[[    -1    -10   -100]
 [   -10   -100  -1000]
 [  -100  -1000 -10000]]


## Vector muliplication

In [7]:
A = np.array([[1,2,3], [4,5,6]])
x = np.array([-1, -10, -100])
b = np.einsum('ij,j->i', A, x)
print(b)

[-321 -654]
